import { Redis } from "@upstash/redis";
import admin from "firebase-admin";
import crypto from "crypto";

/*
|--------------------------------------------------------------------------
| Configuration
|--------------------------------------------------------------------------
*/

const redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL,
    token: process.env.UPSTASH_REDIS_REST_TOKEN
});

const OTP_EXPIRY = 5 * 60; // 5 minutes
const RESEND_COOLDOWN = 30; // 30 seconds
const OTP_MAX_ATTEMPTS = 5;

/*
|--------------------------------------------------------------------------
| Firebase Admin initialization
|--------------------------------------------------------------------------
|
| Required environment variables:
|
| FIREBASE_PROJECT_ID
| FIREBASE_CLIENT_EMAIL
| FIREBASE_PRIVATE_KEY
|
| FIREBASE_PRIVATE_KEY must contain the escaped newlines:
| -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n
|
*/

if (!admin.apps.length) {
    const privateKey = process.env.FIREBASE_PRIVATE_KEY;

    if (
        !process.env.FIREBASE_PROJECT_ID ||
        !process.env.FIREBASE_CLIENT_EMAIL ||
        !privateKey
    ) {
        throw new Error(
            "Missing Firebase Admin environment variables"
        );
    }

    admin.initializeApp({
        credential: admin.credential.cert({
            projectId: process.env.FIREBASE_PROJECT_ID,
            clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
            privateKey: privateKey.replace(/\\n/g, "\n"),
            databaseURL: process.env.FIREBASE_DATABASE_URL
        })
    });
}

const firebaseDb = admin.database();

/*
|--------------------------------------------------------------------------
| Existing secure notification server
|--------------------------------------------------------------------------
*/

const SECURE_NOTIFICATION_URL =
    process.env.SECURE_NOTIFICATION_URL ||
    "https://chat-notification-server.onrender.com/secure-notification";

/*
|--------------------------------------------------------------------------
| Optional internal secret
|--------------------------------------------------------------------------
|
| Recommended:
|
| SECURE_NOTIFICATION_SECRET
|
| Your /secure-notification endpoint should validate this secret.
|
*/

const SECURE_NOTIFICATION_SECRET =
    process.env.SECURE_NOTIFICATION_SECRET || "";

/*
|--------------------------------------------------------------------------
| Helpers
|--------------------------------------------------------------------------
*/

function safeString(value, maxLength = 500) {
    if (value === undefined || value === null) {
        return "";
    }

    return String(value)
        .trim()
        .slice(0, maxLength);
}

function isValidUid(uid) {
    /*
     * Firebase UIDs commonly support letters, numbers,
     * hyphens and underscores.
     *
     * We keep this validation reasonably strict.
     */
    return /^[A-Za-z0-9_-]{1,128}$/.test(uid);
}

function isValidDeviceId(deviceId) {
    /*
     * Android device IDs generated by the application
     * may vary, so allow common safe characters.
     */
    return /^[A-Za-z0-9._:-]{1,256}$/.test(deviceId);
}

function hashOtp(otp) {
    return crypto
        .createHash("sha256")
        .update(otp)
        .digest("hex");
}

function hashDeviceId(deviceId) {
    /*
     * Do not put the raw device ID into the Redis key.
     */
    return crypto
        .createHash("sha256")
        .update(deviceId)
        .digest("hex");
}

function getRedisKey(uid, deviceId) {
    return `appnetick:2fa:otp:${uid}:${hashDeviceId(deviceId)}`;
}

function getCooldownKey(uid, deviceId) {
    return `appnetick:2fa:otp:cooldown:${uid}:${hashDeviceId(deviceId)}`;
}

function generateOtp() {
    /*
     * crypto.randomInt is preferable to Math.random()
     * for security-sensitive OTP generation.
     */
    return String(
        crypto.randomInt(100000, 1000000)
    );
}

function normalizeFirebaseValue(value) {
    if (typeof value === "string") {
        return value.trim();
    }

    return value;
}

/*
|--------------------------------------------------------------------------
| CORS
|--------------------------------------------------------------------------
*/

function setCorsHeaders(res) {
    res.setHeader(
        "Access-Control-Allow-Origin",
        "*"
    );

    res.setHeader(
        "Access-Control-Allow-Methods",
        "POST, OPTIONS"
    );

    res.setHeader(
        "Access-Control-Allow-Headers",
        "Content-Type, Authorization"
    );

    res.setHeader(
        "Cache-Control",
        "no-store"
    );
}

/*
|--------------------------------------------------------------------------
| Get original signup device
|--------------------------------------------------------------------------
*/

async function getSignupDevice(uid) {
    const snapshot = await firebaseDb
        .ref("Users")
        .child(uid)
        .child("deviceInformation")
        .child("signupDevice")
        .once("value");

    if (!snapshot.exists()) {
        return null;
    }

    const data = snapshot.val();

    if (!data || typeof data !== "object") {
        return null;
    }

    const originalDeviceId =
        normalizeFirebaseValue(data.device_id);

    const fcmToken =
        normalizeFirebaseValue(data.fcmToken);

    return {
        deviceId: originalDeviceId || "",
        fcmToken: fcmToken || ""
    };
}

/*
|--------------------------------------------------------------------------
| Send FCM notification
|--------------------------------------------------------------------------
*/

async function sendSecureNotification({
    notificationToken,
    uid,
    newDeviceId,
    otp
}) {
    const notificationBody = {
        notificationToken,
        notificationTitle: "Login Verification",
        notificationBody:
            "A login attempt was made from a new device. Enter the OTP to continue.",
        notificationType: "login_otp",
        notificationSubtext:
            "New device login verification",
        notificationUid: uid,
        notificationDeviceId: newDeviceId,
        otp
    };

    const headers = {
        "Content-Type": "application/json"
    };

    /*
     * If your secure-notification server supports
     * an internal secret, send it.
     */
    if (SECURE_NOTIFICATION_SECRET) {
        headers["x-internal-secret"] =
            SECURE_NOTIFICATION_SECRET;
    }

    const response = await fetch(
        SECURE_NOTIFICATION_URL,
        {
            method: "POST",
            headers,
            body: JSON.stringify(notificationBody)
        }
    );

    let responseData = null;

    try {
        responseData = await response.json();
    } catch (_) {
        responseData = null;
    }

    if (!response.ok) {
        const errorMessage =
            responseData?.error ||
            responseData?.message ||
            `Notification server returned HTTP ${response.status}`;

        throw new Error(errorMessage);
    }

    if (
        !responseData ||
        responseData.success !== true
    ) {
        throw new Error(
            responseData?.error ||
            responseData?.message ||
            "Notification server rejected the request"
        );
    }

    return responseData;
}

/*
|--------------------------------------------------------------------------
| Main Handler
|--------------------------------------------------------------------------
*/

export default async function handler(req, res) {
    setCorsHeaders(res);

    /*
     * Preflight
     */
    if (req.method === "OPTIONS") {
        return res.status(204).end();
    }

    /*
     * Only POST
     */
    if (req.method !== "POST") {
        return res.status(405).json({
            success: false,
            message: "POST only allowed"
        });
    }

    /*
     * Parse request
     */
    try {
        const body = req.body || {};

        const uid = safeString(body.uid, 128);
        const newDeviceId =
            safeString(body.newDeviceId, 256);

        /*
         * Basic validation
         */
        if (!uid) {
            return res.status(400).json({
                success: false,
                message: "UID is required"
            });
        }

        if (!isValidUid(uid)) {
            return res.status(400).json({
                success: false,
                message: "Invalid UID"
            });
        }

        if (!newDeviceId) {
            return res.status(400).json({
                success: false,
                message: "newDeviceId is required"
            });
        }

        if (!isValidDeviceId(newDeviceId)) {
            return res.status(400).json({
                success: false,
                message: "Invalid device ID"
            });
        }

        /*
         * Never allow the new device to request OTP
         * for the original signup device itself.
         *
         * This is an additional safety check.
         */
        const redisKey =
            getRedisKey(uid, newDeviceId);

        const cooldownKey =
            getCooldownKey(uid, newDeviceId);

        /*
         * Check resend cooldown
         */
        const cooldownExists =
            await redis.exists(cooldownKey);

        if (cooldownExists) {
            const ttl =
                await redis.ttl(cooldownKey);

            return res.status(429).json({
                success: false,
                message:
                    "Please wait before requesting another OTP.",
                retryAfter:
                    ttl > 0 ? ttl : RESEND_COOLDOWN
            });
        }

        /*
         * Get original signup device from Firebase.
         *
         * IMPORTANT:
         * We intentionally do NOT accept the FCM token
         * from the Android client.
         */
        const signupDevice =
            await getSignupDevice(uid);

        if (!signupDevice) {
            return res.status(404).json({
                success: false,
                message:
                    "Original signup device not found"
            });
        }

        const originalDeviceId =
            signupDevice.deviceId;

        const originalFcmToken =
            signupDevice.fcmToken;

        if (!originalDeviceId) {
            console.error(
                "2FA OTP: Original device ID missing",
                {
                    uid
                }
            );

            return res.status(404).json({
                success: false,
                message:
                    "Original signup device ID not found"
            });
        }

        if (!originalFcmToken) {
            console.error(
                "2FA OTP: Original FCM token missing",
                {
                    uid,
                    originalDeviceId
                }
            );

            return res.status(404).json({
                success: false,
                message:
                    "Original device notification token not found"
            });
        }

        /*
         * If the requesting device is already the
         * original signup device, OTP should not be
         * treated as a new-device login.
         */
        if (newDeviceId === originalDeviceId) {
            return res.status(400).json({
                success: false,
                message:
                    "This device is already the original signup device"
            });
        }

        /*
         * Generate secure OTP
         */
        const otp = generateOtp();

        /*
         * Store only OTP hash in Redis.
         *
         * The actual OTP is never stored as plaintext.
         */
        const otpHash = hashOtp(otp);

        const otpData = {
            otpHash,
            uid,
            deviceIdHash: hashDeviceId(newDeviceId),
            attempts: 0,
            createdAt: Date.now()
        };

        await redis.set(
            redisKey,
            JSON.stringify(otpData),
            {
                ex: OTP_EXPIRY
            }
        );

        /*
         * Create resend cooldown.
         *
         * This prevents notification spam.
         */
        await redis.set(
            cooldownKey,
            "1",
            {
                ex: RESEND_COOLDOWN
            }
        );

        /*
         * Send OTP to original signup device.
         */
        try {
            await sendSecureNotification({
                notificationToken:
                    originalFcmToken,
                uid,
                newDeviceId,
                otp
            });
        } catch (notificationError) {
            /*
             * Notification failed.
             *
             * Do not leave a valid OTP behind.
             */
            await redis.del(redisKey);
            await redis.del(cooldownKey);

            console.error(
                "2FA OTP notification failed:",
                notificationError
            );

            return res.status(502).json({
                success: false,
                message:
                    "Failed to send login verification OTP"
            });
        }

        /*
         * SUCCESS
         *
         * Never return the OTP itself.
         */
        return res.status(200).json({
            success: true,
            message:
                "Login verification OTP sent successfully",
            expiresIn: OTP_EXPIRY,
            retryAfter: RESEND_COOLDOWN
        });

    } catch (error) {
        console.error(
            "Send 2FA OTP Error:",
            error
        );

        return res.status(500).json({
            success: false,
            message:
                "Failed to send login verification OTP"
        });
    }
}
